spring:
  application:
    name: steve-trains
    prefix: st
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hbm2ddl:
          auto: none
      temp:
        use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      ddl-auto: update
    open-in-view: false
server:
  servlet:
    context-path: /api
  port: ${SERVER_PORT:8898}
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS:50}
      min-spare: ${TOMCAT_MIN_THREADS:20}
    accept-count: ${TOMCAT_ACCEPT_COUNT:300}
    basedir: /
    accesslog:
      enabled: true
      directory: "/logs/steve-trains-service"
      prefix: access_log
      buffered: false
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t %r %s %b %D"

endpoints:
  health:
    enabled: true
  beans:
    enabled: true
  auditevents:
    enabled: true
  configprops:
    enabled: true

eureka:
  instance:
    instanceId: steve-trains-service
    metadata-map:
      management:
        context-path: /api/management
    health-check-url-path: /api/management/health

#postgres:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    jdbcUrl: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:st-dev}?currentSchema=${DB_SCHEMA:train-info}
#    jdbc-read-url: jdbc:postgresql://${POSTGRES_DB_R_HOST:127.0.0.1}:${DB_PORT:5555}/${DB_NAME:crm-dev}?currentSchema=${DB_SCHEMA:oneflow-payment-plan}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:postgres}